"""Create tokens table

Revision ID: 6435de0ffdce
Revises: e5a0c53d96db
Create Date: 2022-07-02 02:02:30.521921

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6435de0ffdce'
down_revision = 'e5a0c53d96db'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tokens',
    sa.Column('id', sa.String(length=256), nullable=False),
    sa.Column('token', sa.Text(), nullable=False),
    sa.Column('salt', sa.Text(), nullable=True),
    sa.Column('expiration', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('tokens')
    # ### end Alembic commands ###
