"""Remove slug from Posts model

Revision ID: 9dc0bc9101df
Revises: 3c092bddd072
Create Date: 2022-07-11 21:00:01.380221

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '9dc0bc9101df'
down_revision = '3c092bddd072'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('slug', table_name='posts')
    op.drop_column('posts', 'slug')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('slug', mysql.VARCHAR(length=20), nullable=False))
    op.create_index('slug', 'posts', ['slug'], unique=False)
    # ### end Alembic commands ###
