"""Add timestamp mixin

Revision ID: b3f0c8eaa809
Revises: a8c82a193e99
Create Date: 2022-07-01 14:18:18.503279

"""
from datetime import datetime
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b3f0c8eaa809'
down_revision = 'a8c82a193e99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('roles', sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.utcnow))
    op.add_column('roles', sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=datetime.utcnow))
    op.add_column('users', sa.Column('created_at', sa.DateTime(), nullable=True, default=datetime.utcnow))
    op.add_column('users', sa.Column('updated_at', sa.DateTime(), nullable=True, onupdate=datetime.utcnow))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'updated_at')
    op.drop_column('users', 'created_at')
    op.drop_column('roles', 'updated_at')
    op.drop_column('roles', 'created_at')
    # ### end Alembic commands ###
